beta

diff --git a/services/base-ubuntu/Dockerfile b/services/base-ubuntu/Dockerfile
--- a/services/base-ubuntu/Dockerfile
+++ b/services/base-ubuntu/Dockerfile
@@ -6,18 +6,68 @@ ARG BUILD_ARCH=amd64
 
 # Environment variables
 ENV \
+    DEBIAN_FRONTEND="noninteractive" \
     HOME="/root" \
     LANG="C.UTF-8" \
     PS1="$(whoami)@$(hostname):$(pwd)$ " \
-    TERM="xterm"
+    S6_BEHAVIOUR_IF_STAGE2_FAILS=2 \
+    S6_CMD_WAIT_FOR_SERVICES=1 \
+    TERM="xterm-256color"
+
+# Set shell
+SHELL ["/bin/bash", "-o", "pipefail", "-c"]
+
+# Install base system
+ARG BUILD_ARCH=amd64
+RUN \
+    apt update -qq -y \
+    \
+    && apt install -qq -y --no-install-recommends \
+        apt-utils \
+        software-properties-common \
+        ca-certificates \
+        curl \
+        jq \
+        tzdata
+
+RUN \
+    S6_ARCH="${BUILD_ARCH}" \
+    && if [ "${BUILD_ARCH}" = "i386" ]; then S6_ARCH="x86"; fi \
+    && if [ "${BUILD_ARCH}" = "armv7" ]; then S6_ARCH="arm"; fi \
+    && if [ $(echo "${BUILD_ARCH}" | sed 's/amd64.*/amd64/') = 'amd64' ]; then S6_ARCH="amd64"; fi \
+    && if [ $(echo "${BUILD_ARCH}" | sed 's/arm64.*/arm64/') = 'arm64' ]; then S6_ARCH="aarch64"; fi \
+    \
+    && curl -L -s "https://github.com/just-containers/s6-overlay/releases/download/v2.0.0.1/s6-overlay-${S6_ARCH}.tar.gz" \
+        | tar zxvf - -C / \
+    \
+    && mkdir -p /etc/fix-attrs.d \
+    && mkdir -p /etc/services.d
+
+RUN \
+    curl -J -L -o /tmp/bashio.tar.gz \
+        "https://github.com/hassio-addons/bashio/archive/v0.10.1.tar.gz" \
+    && mkdir /tmp/bashio \
+    && tar zxvf \
+        /tmp/bashio.tar.gz \
+        --strip 1 -C /tmp/bashio \
+    \
+    && mv /tmp/bashio/lib /usr/lib/bashio \
+    && ln -s /usr/lib/bashio/bashio /usr/bin/bashio
 
 RUN apt-get update && apt-get install -q -y --no-install-recommends \
-    curl \
     socat \
     jq \
-  \
-  && rm -fr \
-    /tmp/*
+    bc 
+
+# cleanup
+RUN apt clean -qq -y && apt autoremove -qq -y && \
+      rm -fr \
+      /tmp/* \
+      /var/{cache,log}/* \
+      /var/lib/apt/lists/*
+
+# Entrypoint & CMD
+ENTRYPOINT [ "/init" ]
 
 # Copy root file-system
 COPY rootfs /
@@ -35,8 +85,8 @@ LABEL \
     org.label-schema.build-date="${BUILD_DATE}" \
     org.label-schema.build-arch="${BUILD_ARCH}" \
     org.label-schema.name="base-ubuntu" \
-    org.label-schema.description="base ubuntu container" \ 
-    org.label-schema.vcs-url="http://github.com/dcmartin/open-horizon/tree/master/base-ubuntu/" \ 
+    org.label-schema.description="Base container for Ubuntu18.04" \ 
+    org.label-schema.vcs-url="http://github.com/dcmartin/open-horizon/tree/master/services/base-ubuntu/" \ 
     org.label-schema.vcs-ref="${BUILD_REF}" \ 
     org.label-schema.version="${BUILD_VERSION}" \
     org.label-schema.vendor="David C Martin <github@dcmartin.com>"
